<?xml version="1.0"?>
<package format="3">
  <name>eps_mirror</name>
  <version>0.2.0</version>
  <description>EPS Kinova simulation and real trajectory routing</description>
  <maintainer email="CHOI-HYOJUN-kr@users.noreply.github.com">Hyojun Choi</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
